name: flutter_study
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  english_words: ^3.1.0  # 包含数千个最常用的英文单词以及一些实用功能.
  # Flutter 常用工具类库 https://github.com/Sky24n/flustars
#  flustars: 0.2.5
  # 轻量级的存储类
  shared_preferences: "^0.4.2"
  groovin_material_icons: ^1.1.5
  # Toast插件 https://github.com/OpenFlutter/flutter_oktoast
  oktoast: ^2.1.8
  # 网络库 https://github.com/flutterchina/dio
  dio: ^2.1.7
  # 引入dio以及jsonAnnotation做数据解析使用
  json_annotation: ^2.4.0
  # https://github.com/ReactiveX/rxdart
  rxdart: ^0.21.0
  # Dart 常用工具类库 https://github.com/Sky24n/common_utils
  common_utils: ^1.1.1
  # Flutter UI组件库 https://github.com/flutterchina/flukit.
  flukit: ^1.0.0
  # 启动URL的插件 https://github.com/flutter/plugins/tree/master/packages/url_launcher
  url_launcher: 5.0.2
  # 图片选择插件 https://github.com/flutter/plugins/tree/master/packages/image_picker
  image_picker: 0.6.0+8
  # 侧滑删除 https://github.com/letsar/flutter_slidable
  flutter_slidable: ^0.5.3
  # WebView插件 https://github.com/flutter/plugins/tree/master/packages/webview_flutter
  webview_flutter: 0.3.7+1
  # 处理键盘事件 https://github.com/diegoveloper/flutter_keyboard_actions
  keyboard_actions: ^2.1.1
  # 列表悬浮头 https://github.com/fluttercommunity/flutter_sticky_headers
  sticky_headers: ^0.1.8
  # 城市选择列表 https://github.com/flutterchina/azlistview
  azlistview: ^0.1.2
  # 用于日历功能 https://github.com/apptreesoftware/date_utils
  date_utils: ^0.1.0+2
  # 手势识别 https://github.com/aleksanderwozniak/simple_gesture_detector
  simple_gesture_detector: ^0.1.3
  # 曲线图表 https://github.com/aeyrium/bezier-chart
  # bezier_chart: ^1.0.7
  # 路由框架 https://github.com/theyakka/fluro
  fluro: ^1.4.0
  # 图片缓存 https://github.com/renefloor/flutter_cached_network_image
  cached_network_image: ^0.8.0
  # 格式化String https://github.com/Naddiseo/dart-sprintf
  sprintf: ^4.0.2
  # toast插件 https://github.com/PonnamKarthik/FlutterToast
  fluttertoast: ^3.1.3
  web_socket_channel: ^1.0.13
  # AMap location plugin for flutter.高德地图定位插件
  amap_location: ^0.2.0
#  simple_permissions: ^0.1.9
  easy_alert: ^0.0.2
  # 指纹认证模块
#  local_auth: ^0.5.2+3  # androidX
  local_auth: ^0.4.0+1
  get_it: ^1.0.3+2
  # 图标库
  font_awesome_flutter: ^8.0.1
  #eventbus
  event_bus: ^1.1.0
  # flutter_webview_plugin
  flutter_webview_plugin: ^0.3.5
  #状态管理
  provider: ^3.0.0+1
  #数据库
  sqflite: ^1.1.5


dev_dependencies:
  flutter_test:
    sdk: flutter

  # dev
  json_serializable: ^3.0.0
  build_runner: ^1.0.0


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/
    - assets/data/
    - assets/images/
    - assets/images/home/
    - assets/images/store/
    - assets/images/state/
    - assets/images/order/
    - assets/images/login/
    - assets/images/goods/
    - assets/images/shop/
    - assets/images/account/
    - assets/images/statistic/
    - assets/images/illustration_1.jpg
    - assets/images/illustration_2.jpg
    - assets/images/illustration_3.jpg
    - assets/images/illustration_4.jpg
    - assets/images/illustration_5.jpg
    - assets/images/illustration_6.jpg
    - assets/images/illustration_7.jpg
    - assets/images/illustration_8.jpg
    - assets/images/illustration_9.jpg
    - assets/images/illustration_10.jpg
    - assets/images/illustration_11.jpg
    - assets/images/illustration_12.jpg
    - assets/images/illustration_13.jpg
    - assets/images/illustration_14.jpg
    - assets/images/illustration_15.jpg
    - assets/images/illustration_16.jpg
    - assets/images/illustration_17.jpg
    - assets/images/illustration_18.jpg
    - assets/images/illustration_19.jpg
    - assets/images/illustration_20.jpg
    - assets/images/illustration_21.jpg
    - assets/images/illustration_22.jpg
    - assets/images/illustration_23.jpg
    - assets/images/illustration_24.jpg
    - assets/images/illustration_25.jpg
    - assets/images/illustration_26.jpg
    - assets/images/illustration_27.jpg
    - assets/images/illustration_28.jpg
    - assets/images/illustration_29.jpg
    - assets/images/illustration_30.jpg
    - assets/images/illustration_31.jpg
    - assets/images/illustration_32.jpg
    - assets/images/illustration_33.jpg
    - assets/images/illustration_34.jpg
    - assets/images/illustration_35.jpg
    - assets/images/cat.jpeg
    - assets/images/1.jpeg
    - assets/images/2.jpeg
    - assets/images/3.jpeg
    - assets/images/4.jpeg
    - assets/images/5.jpeg
    - assets/images/6.jpeg
    - assets/images/7.jpeg
    - assets/images/8.jpeg
    - assets/images/9.jpeg
    - assets/images/login_logo.png
    - assets/images/logo-github.png

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  fonts:
    - family: myfont
      fonts:
          - asset: fonts/myfont.ttf
    - family: WorkSansSemiBold
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-SemiBold.ttf
    - family: WorkSansBold
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Bold.ttf
    - family: WorkSansMedium
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Medium.ttf


  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
